name: Investigate `github.event_name`
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "33 * * * *" # 3 min from now
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Report event name
        run: echo "$GITHUB_EVENT_NAME"
