name: Investigate `github.event_name`
on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 min
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Report event name
        run: echo "$GITHUB_EVENT_NAME"
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Report event name
        run: echo "$GITHUB_EVENT_NAME"
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: [test1, test2]
    if: ( failure() || cancelled() ) && github.repository_owner == 'jdblischak' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        env:
          GH_TOKEN: ${{ github.token }}
          TZ: "America/New_York"
        run: |
          theDate="$(date '+%A (%Y-%m-%d)')"
          theMessage="Scheduled build failed on $theDate in run [$GITHUB_RUN_ID]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"

          existing=$(gh issue list \
            --label "bug" \
            --limit 1 \
            --jq '.[].number' \
            --json "number" \
            --state "open")

          if [[ -z "$existing" ]]
          then
            # open new issue
            gh issue create \
              --body "$theMessage" \
              --label "bug" \
              --title "Scheduled build failed on $theDate"
          else
            # comment on existing issue
            gh issue comment "$existing" \
              --body "$theMessage"
          fi
