name: Investigate `github.event_name`
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 5 min
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Report event name
        run: echo "$GITHUB_EVENT_NAME"
      - name: error in test1
        run: stop
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Report event name
        run: echo "$GITHUB_EVENT_NAME"
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: [test1, test2]
    if: ( failure() || cancelled() ) && github.repository_owner == 'jdblischak'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        env:
          GH_TOKEN: ${{ github.token }}
          TZ: "America/New_York"
        run: |
          gh issue list \
            --label "bug" \
            --state "open"

          gh issue create \
            --body "Scheduled build failed in run [$GITHUB_RUN_ID]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
            --label "bug" \
            --title "Scheduled build failed on $(date '+%A (%Y-%m-%d)')"
